--- #YAML:1.0
name:                Devel-Dt
version:             0.02
abstract:            Kind of emulates command line flag -Dt on normal perl
license:             ~
author:              
    - Joshua ben Jore <jjore@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    B::Utils:                      0
    Runops::Trace:                 0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
